# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/fedex_home.yaml
class Fedex_homeDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_fedex_home
{Date.civil(2015,1,1) => 'New Year\'s Day',
 Date.civil(2015,1,2) => 'Day After New Year\'s Day',
 Date.civil(2016,3,27) => 'Easter',
 Date.civil(2015,5,25) => 'Memorial Day',
 Date.civil(2015,5,26) => 'Day After Memorial Day',
 Date.civil(2015,7,3) => 'Day Before Independence Day',
 Date.civil(2015,7,4) => 'Independence Day',
 Date.civil(2015,7,5) => 'Day After Independence Day',
 Date.civil(2015,9,7) => 'Labor Day',
 Date.civil(2016,9,6) => 'Day After Labor Day',
 Date.civil(2016,11,24) => 'Thanksgiving',
 Date.civil(2015,12,24) => 'Christmas Eve',
 Date.civil(2015,12,25) => 'Christmas Day',
 Date.civil(2015,12,26) => 'Day After Christmas'}.each do |date, name|
  assert_equal name, (Holidays.on(date, :fedex_home)[0] || {})[:name]
end

  end
end
