# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/fedex_ground.yaml
class Fedex_groundDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_fedex_ground
{Date.civil(2015,1,1) => 'New Year\'s Day',
 Date.civil(2015,1,2) => 'Day After New Year\'s Day',
 Date.civil(2016,3,27) => 'Easter',
 Date.civil(2015,5,25) => 'Memorial Day',
 Date.civil(2015,7,4) => 'Independence Day',
 Date.civil(2015,9,5) => 'Saturday Before Labor Day',
 Date.civil(2015,9,6) => 'Sunday Before Labor Day',
 Date.civil(2015,9,7) => 'Labor Day',
 Date.civil(2016,11,24) => 'Thanksgiving',
 Date.civil(2016,11,26) => 'Saturday After Thanksgiving',
 Date.civil(2015,12,23) => 'Day Before Christmas Eve',
 Date.civil(2015,12,24) => 'Christmas Eve',
 Date.civil(2015,12,25) => 'Christmas Day',
 Date.civil(2015,12,26) => 'Day After Christmas',
 Date.civil(2015,12,31) => 'New Year\'s Eve',}.each do |date, name|
  assert_equal name, (Holidays.on(date, :fedex_ground)[0] || {})[:name]
end

  end
end
