# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: definitions/fedex_home.yaml
  #
  # To use the definitions in this file, load it right after you load the
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'generated_definitions/fedex_home'
  #
  # All the definitions are available at https://github.com/holidays/holidays
  module FEDEX_HOME # :nodoc:
    def self.defined_regions
      [:fedex_home]
    end

    def self.holidays_by_month
      {
              0 => [{:function => "easter(year)", :function_arguments => [:year], :name => "Easter", :regions => [:fedex_home]}],
      1 => [{:mday => 1, :observed => "to_weekday_if_weekend(date)", :observed_arguments => [:date], :name => "New Year's Day", :regions => [:fedex_home]},
            {:mday => 2, :name => "Day After New Year's Day", :regions => [:fedex_home]}],
      5 => [{:wday => 1, :week => -1, :name => "Memorial Day", :regions => [:fedex_home]},
            {:wday => 2, :week => -1, :name => "Day After Memorial Day", :regions => [:fedex_home]}],
      7 => [{:mday => 3, :name => "Day Before Independence Day", :regions => [:fedex_home]},
            {:mday => 4, :observed => "to_weekday_if_weekend(date)", :observed_arguments => [:date], :name => "Independence Day", :regions => [:fedex_home]},
            {:mday => 5, :name => "Day After Independence Day", :regions => [:fedex_home]}],
      9 => [{:wday => 1, :week => 1, :name => "Labor Day", :regions => [:fedex_home]},
            {:wday => 2, :week => 1, :name => "Day After Labor Day", :regions => [:fedex_home]}],
      11 => [{:wday => 4, :week => 4, :name => "Thanksgiving", :regions => [:fedex_home]}],
      12 => [{:mday => 24, :name => "Christmas Eve", :regions => [:fedex_home]},
            {:mday => 25, :name => "Christmas Day", :regions => [:fedex_home]},
            {:mday => 26, :name => "Day After Christmas", :regions => [:fedex_home]}]
      }
    end

    def self.custom_methods
      {
        
      }
    end
  end
end
