# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: definitions/fedex_ground.yaml
  #
  # To use the definitions in this file, load it right after you load the
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'generated_definitions/fedex_ground'
  #
  # All the definitions are available at https://github.com/holidays/holidays
  module FEDEX_GROUND # :nodoc:
    def self.defined_regions
      [:fedex_ground]
    end

    def self.holidays_by_month
      {
              0 => [{:function => "easter(year)", :function_arguments => [:year], :name => "Easter", :regions => [:fedex_ground]}],
      1 => [{:mday => 1, :observed => "to_weekday_if_weekend(date)", :observed_arguments => [:date], :name => "New Year's Day", :regions => [:fedex_ground]},
            {:mday => 2, :name => "Day After New Year's Day", :regions => [:fedex_ground]}],
      5 => [{:wday => 1, :week => -1, :name => "Memorial Day", :regions => [:fedex_ground]}],
      7 => [{:mday => 3, :name => "Day Before Independence Day", :regions => [:fedex_ground]},
            {:mday => 4, :observed => "to_weekday_if_weekend(date)", :observed_arguments => [:date], :name => "Independence Day", :regions => [:fedex_ground]}],
      9 => [{:function => "saturday_before_labor_day(year)", :function_arguments => [:year], :name => "Saturday Before Labor Day", :regions => [:fedex_ground]},
            {:function => "sunday_before_labor_day(year)", :function_arguments => [:year], :name => "Sunday Before Labor Day", :regions => [:fedex_ground]},
            {:wday => 1, :week => 1, :name => "Labor Day", :regions => [:fedex_ground]}],
      11 => [{:wday => 4, :week => 4, :name => "Thanksgiving", :regions => [:fedex_ground]},
            {:function => "saturday_after_thanksgiving(year)", :function_arguments => [:year], :name => "Saturday After Thanksgiving", :regions => [:fedex_ground]}],
      12 => [{:mday => 23, :name => "Day Before Christmas Eve", :regions => [:fedex_ground]},
            {:mday => 24, :name => "Christmas Eve", :regions => [:fedex_ground]},
            {:mday => 25, :name => "Christmas Day", :regions => [:fedex_ground]},
            {:mday => 26, :name => "Day After Christmas", :regions => [:fedex_ground]},
            {:mday => 31, :name => "New Year's Eve", :regions => [:fedex_ground]}]
      }
    end

    def self.custom_methods
      {
        "sunday_before_labor_day(year)" => Proc.new { |year|
Holidays::Factory::DateCalculator.day_of_month_calculator.call(year, 9, 1, 1) - 1
},

"saturday_before_labor_day(year)" => Proc.new { |year|
Holidays::Factory::DateCalculator.day_of_month_calculator.call(year, 9, 1, 1) - 2
},

"saturday_after_thanksgiving(year)" => Proc.new { |year|
Holidays::Factory::DateCalculator.day_of_month_calculator.call(year, 11, 4, 4) + 2
},


      }
    end
  end
end
